name: libvirt
version: 2.4.0
summary: Libvirt Daemon
description: Don't use this its just for testing.
grade: devel
confinement: classic

apps:
  libvirt-bin:
    command: sbin/libvirtd
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
  virsh:
    command: bin/virsh
    plugs:
      - network

parts:
  qemu:
    source: http://wiki.qemu-project.org/download/qemu-2.7.0.tar.bz2
    plugin: autotools
    build-packages:
      - libaio-dev
      - acpica-tools
      - libasound2-dev
      - libattr1-dev
      - libcap-dev
      - libcap-ng-dev
      - libiscsi-dev
      - libnuma-dev
      - librados-dev
      - librbd-dev
      - libspice-server-dev
      - libspice-protocol-dev
      - libusb-1.0-0-dev
      - libusbredirparser-dev
      - zlib1g-dev
      - uuid-dev
    stage-packages:
      - libxml2
      - libyajl2
      - libnuma1
      - libaio1
      - libiscsi2
      - libcurl3-gnutls
      - librbd1
      - librados2
      - libcairo2
      - libgdk-pixbuf2.0-0
      - libpixman-1-0
      - libgtk2.0-0
      - libspice-server1
      - libusb-1.0-0
      - libusbredirparser1
      - libx11-6
    configflags:
        - "--target-list=x86_64-softmmu i386-softmmu"
        - "--prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current"

    organize:
      # Hack to shift installed qemu back to root of snap
      # required to ensure that pathing to files etc works at
      # runtime
      # * is not used to avoid directory merge conflicts
      "snap/libvirt/current/": "./"
  libvirt:
    source: https://libvirt.org/sources/libvirt-2.4.0.tar.xz
    plugin: autotools
    build-packages:
      - libxml2-dev
      - libcurl4-gnutls-dev
      - libncurses5-dev
      - libreadline-dev
      - zlib1g-dev
      - libgcrypt20-dev
      - libgnutls28-dev
      - libsasl2-dev
      - libsanlock-dev
      - libiscsi-dev
      - librbd-dev
      - librados-dev
      - libyajl-dev
      - libpcap0.8-dev
      - libaudit-dev
      - libdevmapper-dev
      - libpciaccess-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libpolkit-gobject-1-dev
      - uuid-dev
      - libnuma-dev
      - python-all
      - python-six
    stage-packages:
      - libxml2
      - libyajl2
      - libnuma1
      - libcurl3-gnutls
    configflags:
        - "--with-qemu"
        - "--without-xen"
        - "--without-openvz"
        - "--without-vmware"
        - "--without-xenapi"
        - "--without-esx"
        - "--without-hyperv"
        - "--without-lxc"
        - "--without-vz"
        - "--without-vbox"
        - "--without-uml"
        - "--without-sasl"
        - "--prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current"
        - "--localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common"
    organize:
      # Hack to shift installed libvirt back to root of snap
      # required to ensure that pathing to files etc works at
      # runtime
      # * is not used to avoid directory merge conflicts
      "snap/libvirt/current/": "./"
    filesets:
      all:
        - -etc/libvirt/libvirtd.conf
    stage: [$all]
    prime: [$all]
  templates:
    after:
      - libvirt
      - qemu
    source: snap
    plugin: dump
